
version: '3.7'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - ".env"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  tgbot:
    build: .
    volumes:
      - .:/src
    command: python app.py
    restart: always\

    env_file:
      - ".env"
